# -*- coding: utf-8 -*-
"""120_years_of_Olympic_history_Preprocessing (1) (1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mMF6rW7z_UiHpR6Tf5p-cGlSTcKGfGs7

#Data Loading
"""

!pip install kaggle
!mkdir -p ~/.kaggle
!mv kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

!kaggle datasets download -d heesoo37/120-years-of-olympic-history-athletes-and-results
!unzip 120-years-of-olympic-history-athletes-and-results.zip

import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

import pandas as pd
df = pd.read_csv('athlete_events.csv')
print(df.head())

"""#EDA"""

print(f"Shape of df is{df.shape}")
df.describe()

df = df.drop('ID', axis = 1)
df = df.drop('Games', axis = 1)
eda_summary = {
    "Missing Values": df.isnull().sum(),
    "Averages (Mean)": df.mean(numeric_only=True),
    "Unique Values": df.nunique()
}
eda_summary_df = pd.DataFrame(eda_summary)
print("Basic EDA Summaries:")
print(eda_summary_df)

# Select numeric features
numeric_features = df.select_dtypes(include=np.number)

# Create distribution plots
plt.figure(figsize=(15, 10))
for i, column in enumerate(numeric_features.columns, 1):
    plt.subplot(3, 3, i)
    sns.histplot(numeric_features[column].dropna(), kde=True, bins=30)
    plt.title(f"Distribution of {column}")
plt.tight_layout()
plt.show()

# Mode values and unique counts for categorical columns
categorical_modes = df.select_dtypes(include="object").mode().iloc[0]
unique_values_per_cat = df.select_dtypes(include="object").nunique()

# Create a DataFrame for categorical modes and unique values
cat_modes_df = pd.DataFrame({
    "Mode": categorical_modes,
    "Unique Values": unique_values_per_cat
})
print("Categorical Modes and Unique Values:")
print(cat_modes_df)

# Compute variances
variances = df.var(numeric_only=True)

# Plot variances
plt.figure(figsize=(10, 6))
variances.sort_values().plot(kind="barh", color="skyblue", edgecolor="black")
plt.title("Variance of Numeric Features")
plt.xlabel("Variance")
plt.ylabel("Columns")
plt.tight_layout()
plt.show()

"""#Preprocessing"""

df = df.apply(
    lambda col: col.fillna(-1) if col.dtypes in [np.float64, np.int64] else col.fillna("MISSING")
)

# Save preprocessed csv
df.to_csv("preprocessed_athlete_events.csv", index=False)

df.head()